# Generated by Django 5.2.15 on 2026-07-02 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0003_alter_imagemrifa_criado_em_alter_imagemrifa_imagem_and_more'),
        ('vendedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedorrifa',
            options={'ordering': ['rifa__titulo'], 'verbose_name': 'rifa associada', 'verbose_name_plural': 'rifas associadas'},
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='comissao_fixa',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='comissao por numero'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendedores', to=settings.AUTH_USER_MODEL, verbose_name='organizador'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='vendedorrifa',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='associacao ativa'),
        ),
        migrations.AlterField(
            model_name='vendedorrifa',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='vendedorrifa',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='vendedorrifa',
            name='rifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores_associados', to='rifas.rifa', verbose_name='rifa'),
        ),
        migrations.AlterField(
            model_name='vendedorrifa',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rifas_associadas', to='vendedores.vendedor', verbose_name='vendedor'),
        ),
    ]
