# Generated by Django 5.2.15 on 2026-07-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0002_alter_vendedorrifa_options_alter_vendedor_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardVendedor',
            fields=[
            ],
            options={
                'verbose_name': 'dashboard do vendedor',
                'verbose_name_plural': 'dashboard do vendedor',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vendedores.vendedor',),
        ),
    ]
