# Generated by Django 5.2.15 on 2026-06-26 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('descricao_html', models.TextField(blank=True)),
                ('valor_numero', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_numeros', models.PositiveIntegerField()),
                ('data_sorteio', models.DateTimeField()),
                ('chave_pix', models.CharField(max_length=150)),
                ('tempo_reserva', models.PositiveIntegerField(default=15)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativa', 'Ativa'), ('encerrada', 'Encerrada')], default='rascunho', max_length=20)),
                ('imagem_principal', models.FileField(blank=True, upload_to='rifas/principais/')),
                ('link_transmissao', models.URLField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rifas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rifa',
                'verbose_name_plural': 'rifas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='rifas/galeria/')),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_galeria', to='rifas.rifa')),
            ],
            options={
                'verbose_name': 'imagem da galeria',
                'verbose_name_plural': 'imagens da galeria',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveSmallIntegerField()),
                ('descricao', models.TextField()),
                ('imagem', models.FileField(blank=True, upload_to='rifas/premios/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='rifas.rifa')),
            ],
            options={
                'verbose_name': 'premio',
                'verbose_name_plural': 'premios',
                'ordering': ['posicao'],
                'constraints': [models.UniqueConstraint(fields=('rifa', 'posicao'), name='premio_unico_por_posicao')],
            },
        ),
        migrations.CreateModel(
            name='NumeroRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='disponivel', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='rifas.rifa')),
            ],
            options={
                'verbose_name': 'numero da rifa',
                'verbose_name_plural': 'numeros da rifa',
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('rifa', 'numero'), name='numero_unico_por_rifa')],
            },
        ),
    ]
