# Generated by Django 5.2.15 on 2026-07-02 21:21

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def preencher_slugs_e_status(apps, schema_editor):
    Rifa = apps.get_model('rifas', 'Rifa')
    NumeroRifa = apps.get_model('rifas', 'NumeroRifa')

    usados = set(Rifa.objects.exclude(slug__isnull=True).exclude(slug='').values_list('slug', flat=True))
    for rifa in Rifa.objects.filter(models.Q(slug__isnull=True) | models.Q(slug='')).order_by('id'):
        base_slug = slugify(rifa.titulo) or f'rifa-{rifa.pk}'
        slug = base_slug
        contador = 1
        while slug in usados:
            contador += 1
            slug = f'{base_slug}-{contador}'
        rifa.slug = slug
        rifa.save(update_fields=['slug'])
        usados.add(slug)

    NumeroRifa.objects.filter(status='vendido').update(status='pago')


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0001_initial'),
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='numerorifa',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponivel'), ('reservado', 'Reservado'), ('aguardando_aprovacao', 'Aguardando aprovacao'), ('pago', 'Pago')], default='disponivel', max_length=20),
        ),
        migrations.RunPython(preencher_slugs_e_status, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador_nome', models.CharField(max_length=150)),
                ('comprador_email', models.EmailField(max_length=254)),
                ('comprador_telefone', models.CharField(max_length=20)),
                ('comprador_cpf', models.CharField(max_length=14)),
                ('data_expiracao', models.DateTimeField()),
                ('status', models.CharField(choices=[('reservada', 'Reservada'), ('aguardando_aprovacao', 'Aguardando aprovacao'), ('paga', 'Paga'), ('expirada', 'Expirada'), ('rejeitada', 'Rejeitada')], default='reservada', max_length=30)),
                ('comprovante', models.FileField(blank=True, upload_to='comprovantes/')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='rifas.rifa')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='vendedores.vendedor')),
            ],
            options={
                'verbose_name': 'transacao',
                'verbose_name_plural': 'transacoes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_transacao', to='rifas.numerorifa')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='rifas.transacao')),
            ],
            options={
                'verbose_name': 'item da transacao',
                'verbose_name_plural': 'itens da transacao',
                'ordering': ['numero__numero'],
            },
        ),
    ]
