# Generated by Django 5.2.15 on 2026-07-02 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0002_rifa_slug_alter_numerorifa_status_transacao_and_more'),
        ('vendedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemrifa',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='imagemrifa',
            name='imagem',
            field=models.FileField(upload_to='rifas/galeria/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='imagemrifa',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='ordem'),
        ),
        migrations.AlterField(
            model_name='imagemrifa',
            name='rifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_galeria', to='rifas.rifa', verbose_name='rifa'),
        ),
        migrations.AlterField(
            model_name='itemtransacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='itemtransacao',
            name='numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_transacao', to='rifas.numerorifa', verbose_name='numero'),
        ),
        migrations.AlterField(
            model_name='itemtransacao',
            name='transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='rifas.transacao', verbose_name='transacao'),
        ),
        migrations.AlterField(
            model_name='itemtransacao',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor unitario'),
        ),
        migrations.AlterField(
            model_name='numerorifa',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='numerorifa',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='numerorifa',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='numero'),
        ),
        migrations.AlterField(
            model_name='numerorifa',
            name='rifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='rifas.rifa', verbose_name='rifa'),
        ),
        migrations.AlterField(
            model_name='numerorifa',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponivel'), ('reservado', 'Reservado'), ('aguardando_aprovacao', 'Aguardando aprovacao'), ('pago', 'Pago')], default='disponivel', max_length=20, verbose_name='status do numero'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='descricao',
            field=models.TextField(verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='imagem',
            field=models.FileField(blank=True, upload_to='rifas/premios/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='posicao',
            field=models.PositiveSmallIntegerField(verbose_name='posicao'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='rifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='rifas.rifa', verbose_name='rifa'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='chave_pix',
            field=models.CharField(max_length=150, verbose_name='chave Pix'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='data_sorteio',
            field=models.DateTimeField(verbose_name='data do sorteio'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='descricao_html',
            field=models.TextField(blank=True, verbose_name='descricao formatada'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='excluido em'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='imagem_principal',
            field=models.FileField(blank=True, upload_to='rifas/principais/', verbose_name='imagem principal'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='link_transmissao',
            field=models.URLField(blank=True, verbose_name='link da transmissao'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rifas', to=settings.AUTH_USER_MODEL, verbose_name='organizador'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True, verbose_name='slug publico'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('ativa', 'Ativa'), ('encerrada', 'Encerrada')], default='rascunho', max_length=20, verbose_name='status da rifa'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='tempo_reserva',
            field=models.PositiveIntegerField(default=15, verbose_name='tempo de reserva em minutos'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='total_numeros',
            field=models.PositiveIntegerField(verbose_name='total de numeros'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='valor_numero',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor do numero'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='comprador_cpf',
            field=models.CharField(max_length=14, verbose_name='CPF do comprador'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='comprador_email',
            field=models.EmailField(max_length=254, verbose_name='e-mail do comprador'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='comprador_nome',
            field=models.CharField(max_length=150, verbose_name='nome do comprador'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='comprador_telefone',
            field=models.CharField(max_length=20, verbose_name='telefone do comprador'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='comprovante',
            field=models.FileField(blank=True, upload_to='comprovantes/', verbose_name='comprovante'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data_expiracao',
            field=models.DateTimeField(verbose_name='data de expiracao'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='rifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='rifas.rifa', verbose_name='rifa'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='status',
            field=models.CharField(choices=[('reservada', 'Reservada'), ('aguardando_aprovacao', 'Aguardando aprovacao'), ('paga', 'Paga'), ('expirada', 'Expirada'), ('rejeitada', 'Rejeitada')], default='reservada', max_length=30, verbose_name='status da transacao'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor total'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='vendedores.vendedor', verbose_name='vendedor'),
        ),
    ]
